[project]
name = "hello_world"
version = "0.1.0"
entry-point = "main.jac"

[dependencies]
google = ">=0.0.0"
google-genai = ">=0.0.0"

[dependencies.npm]
jac-client-node = "1.0.4"

[dependencies.npm.dev]
"@jac-client/dev-deps" = "1.0.0"

[serve]
base_route_app = "app"

[plugins.client]
